"""empty message

Revision ID: 9bc95be1738b
Revises: 2974dcf09043
Create Date: 2021-06-02 22:53:20.807819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc95be1738b'
down_revision = '2974dcf09043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('delivered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'delivered')
    # ### end Alembic commands ###
